// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller.js"
application.register("carousel", CarouselController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import EditTagsController from "./edit_tags_controller.js"
application.register("edit-tags", EditTagsController)

import EntityAutocompleteController from "./entity_autocomplete_controller.js"
application.register("entity-autocomplete", EntityAutocompleteController)

import EntityEditController from "./entity_edit_controller.js"
application.register("entity-edit", EntityEditController)

import EntityMatcherController from "./entity_matcher_controller.js"
application.register("entity-matcher", EntityMatcherController)

import EntityMergeController from "./entity_merge_controller.js"
application.register("entity-merge", EntityMergeController)

import Fec__ContributionsTableController from "./fec/contributions_table_controller.js"
application.register("fec--contributions-table", Fec__ContributionsTableController)

import Fec__MatchContributionsController from "./fec/match_contributions_controller.js"
application.register("fec--match-contributions", Fec__MatchContributionsController)

import HomeDatatablesController from "./home_datatables_controller.js"
application.register("home-datatables", HomeDatatablesController)

import ImageCropperController from "./image_cropper_controller.js"
application.register("image-cropper", ImageCropperController)

import ImageEditorController from "./image_editor_controller.js"
application.register("image-editor", ImageEditorController)

import ListDatatableController from "./list_datatable_controller.js"
application.register("list-datatable", ListDatatableController)

import ListSettingsController from "./list_settings_controller.js"
application.register("list-settings", ListSettingsController)

import ListsSearchController from "./lists_search_controller.js"
application.register("lists-search", ListsSearchController)

import MatchContributionsController from "./match_contributions_controller.js"
application.register("match-contributions", MatchContributionsController)

import NavigationFormController from "./navigation_form_controller.js"
application.register("navigation-form", NavigationFormController)

import NavmenuController from "./navmenu_controller.js"
application.register("navmenu", NavmenuController)

import NewEntityFormController from "./new_entity_form_controller.js"
application.register("new-entity-form", NewEntityFormController)

import OligrapherController from "./oligrapher_controller.js"
application.register("oligrapher", OligrapherController)

import OligrapherSearchController from "./oligrapher_search_controller.js"
application.register("oligrapher-search", OligrapherSearchController)

import Profile__ConnectionsTableController from "./profile/connections_table_controller.js"
application.register("profile--connections-table", Profile__ConnectionsTableController)

import Profile__ControlsController from "./profile/controls_controller.js"
application.register("profile--controls", Profile__ControlsController)

import Profile__EditableBlurbController from "./profile/editable_blurb_controller.js"
application.register("profile--editable-blurb", Profile__EditableBlurbController)

import Profile__EntitySummaryController from "./profile/entity_summary_controller.js"
application.register("profile--entity-summary", Profile__EntitySummaryController)

import Profile__ListsDropdownController from "./profile/lists_dropdown_controller.js"
application.register("profile--lists-dropdown", Profile__ListsDropdownController)

import Profile__SubcategoryPaginationController from "./profile/subcategory_pagination_controller.js"
application.register("profile--subcategory-pagination", Profile__SubcategoryPaginationController)

import Profile__SubcategoryToggleController from "./profile/subcategory_toggle_controller.js"
application.register("profile--subcategory-toggle", Profile__SubcategoryToggleController)

import ReferenceWidgetController from "./reference_widget_controller.js"
application.register("reference-widget", ReferenceWidgetController)

import RelationshipBulkAdderController from "./relationship_bulk_adder_controller.js"
application.register("relationship-bulk-adder", RelationshipBulkAdderController)

import RelationshipCreatorController from "./relationship_creator_controller.js"
application.register("relationship-creator", RelationshipCreatorController)

import RelationshipsDatatableLegacyController from "./relationships_datatable_legacy_controller.js"
application.register("relationships-datatable-legacy", RelationshipsDatatableLegacyController)

import ReverseLinkController from "./reverse_link_controller.js"
application.register("reverse-link", ReverseLinkController)

import SidebarSourceLinksController from "./sidebar_source_links_controller.js"
application.register("sidebar-source-links", SidebarSourceLinksController)

import TagFormController from "./tag_form_controller.js"
application.register("tag-form", TagFormController)

import TooltipController from "./tooltip_controller.js"
application.register("tooltip", TooltipController)

import UsernameValidationController from "./username_validation_controller.js"
application.register("username-validation", UsernameValidationController)
