// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ActionTextController from "./action_text_controller.js"
application.register("action-text", ActionTextController)

import CarouselController from "./carousel_controller.js"
application.register("carousel", CarouselController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import DonationMatcherController from "./donation_matcher_controller.js"
application.register("donation-matcher", DonationMatcherController)

import EntityAutocompleteController from "./entity_autocomplete_controller.js"
application.register("entity-autocomplete", EntityAutocompleteController)

import EntityEditController from "./entity_edit_controller.js"
application.register("entity-edit", EntityEditController)

import EntityMatcherController from "./entity_matcher_controller.js"
application.register("entity-matcher", EntityMatcherController)

import EntityMergeController from "./entity_merge_controller.js"
application.register("entity-merge", EntityMergeController)

import EntityPageController from "./entity_page_controller.js"
application.register("entity-page", EntityPageController)

import EntityTagsController from "./entity_tags_controller.js"
application.register("entity-tags", EntityTagsController)

import HomeDatatablesController from "./home_datatables_controller.js"
application.register("home-datatables", HomeDatatablesController)

import ImageCropperController from "./image_cropper_controller.js"
application.register("image-cropper", ImageCropperController)

import ImageEditorController from "./image_editor_controller.js"
application.register("image-editor", ImageEditorController)

import ListDatatableController from "./list_datatable_controller.js"
application.register("list-datatable", ListDatatableController)

import ListSettingsController from "./list_settings_controller.js"
application.register("list-settings", ListSettingsController)

import MatchContributionsController from "./match_contributions_controller.js"
application.register("match-contributions", MatchContributionsController)

import NavigationFormController from "./navigation_form_controller.js"
application.register("navigation-form", NavigationFormController)

import NavmenuController from "./navmenu_controller.js"
application.register("navmenu", NavmenuController)

import NysEntitySearchController from "./nys_entity_search_controller.js"
application.register("nys-entity-search", NysEntitySearchController)

import NysFilerSearchController from "./nys_filer_search_controller.js"
application.register("nys-filer-search", NysFilerSearchController)

import OligrapherController from "./oligrapher_controller.js"
application.register("oligrapher", OligrapherController)

import ReferenceWidgetController from "./reference_widget_controller.js"
application.register("reference-widget", ReferenceWidgetController)

import RelationshipBulkAdderController from "./relationship_bulk_adder_controller.js"
application.register("relationship-bulk-adder", RelationshipBulkAdderController)

import RelationshipCreatorController from "./relationship_creator_controller.js"
application.register("relationship-creator", RelationshipCreatorController)

import RelationshipsDatatableController from "./relationships_datatable_controller.js"
application.register("relationships-datatable", RelationshipsDatatableController)

import SidebarSourceLinksController from "./sidebar_source_links_controller.js"
application.register("sidebar-source-links", SidebarSourceLinksController)

import TooltipController from "./tooltip_controller.js"
application.register("tooltip", TooltipController)

import UsernameValidationController from "./username_validation_controller.js"
application.register("username-validation", UsernameValidationController)
