require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1

Rails:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'app/models/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Naming/MethodParameterName:
  Enabled: false
  Exclude:
    - 'app/models/image.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Style/CommentedKeyword:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'spec/**/*.rb'
    - 'app/indices/*.rb'

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  Exclude:
    - 'config/routes.rb'

Style/NumericLiterals:
  Exclude:
    - 'spec/factories/*.rb'

Style/StringLiterals:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/**/*.rb'

Style/SymbolArray:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true
  Exclude:
    - 'lib/scripts/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/scripts/*.rb'

Layout/HashAlignment:
  Exclude:
    - 'lib/fec/**/*.rb'

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/features/*.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ImplicitSubject:
  Exclude:
    - 'spec/controllers/*.rb'

RSpec/Capybara:
  Capybara/FeatureMethods:
    Enabled: false
