version: 2.1

workflows:
  run_tests:
    jobs:
      - mocha
      - rspec
jobs:
  rspec:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
      resource_class: large

    environment:
      RAILS_ENV: test

    steps:
      - checkout
      - run: bin/build
      - run: docker compose up -d postgres
      - run: timeout 10 sh -c 'while true; do if docker compose exec --user postgres postgres pg_isready; then break; else sleep 1;fi done'
      - run: docker compose run --rm app bundle config path vendor/bundle
      - restore_cache:
          name: Restore bundle cache
          key: vendor-bundle-{{ checksum "Gemfile.lock" }}
      - run: docker compose run --rm app bundle install
      - save_cache:
          key: vendor-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - restore_cache:
          name: Restore npm cache
          key: node-modules-{{ checksum "package-lock.json" }}
      - run: docker compose run --rm app npm install
      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: docker compose run --rm -e RAILS_ENV=test app bundle exec rails db:reset
      - run: docker compose run --rm -e RAILS_ENV=test app bundle exec rails javascript:build
      - run: docker compose run --rm -e RAILS_ENV=test app bundle exec rails assets:precompile
      - run: docker compose run --rm -e RAILS_ENV=test app bundle exec rails ts:configure
      - run: docker compose run --rm -e RAILS_ENV=test -e CIRCLECI=true -e CI=true app bundle exec rspec --format documentation
      - store_test_results:
          path: tmp/rspec

  mocha:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm test
