version: 2.1

jobs:
  rspec:
    environment:
      RAILS_ENV: test
      COVERAGE: yes
    resource_class: medium
    docker:
      - image: ruby:3.0.1-buster
        environment:
          RAILS_ENV: test

      - image: postgres:13
        environment:
          POSTGRES_PASSWORD: littlesis
          POSTGRES_USER: littlesis
          POSTGRES_DB: littlesis_test

    steps:
      - checkout
      - run: bin/ci_setup.sh
      - run: bin/docker_setup.sh

      - restore_cache:
          keys:
            - gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec rake db:schema:load
      - run: bundle exec rake tmp:clear

      - restore_cache:
          keys:
            - node-modules-cache-v1-{{ checksum "yarn.lock" }}

      - run: bundle exec rake yarn:install

      - save_cache:
          key: node-modules-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: bundle exec rake webpacker:compile
      - run: bundle exec rake assets:precompile
      - run: bundle exec rspec --format documentation --format RspecJunitFormatter -o ./tmp/rspec/rspec.xml

      - store_test_results:
          path: tmp/rspec

      - store_artifacts:
          path: coverage

  mocha:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --immutable

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn test

workflows:
  rspec:
    jobs:
      - rspec
      - mocha
