export const exampleMatch = {
  "entity": {
    "id": 109722,
    "name": "Joy Pollock",
    "blurb": null,
    "summary": null,
    "website": null,
    "parent_id": null,
    "primary_ext": "Person",
    "created_at": "2012-12-09T14:05:18.000Z",
    "updated_at": "2012-12-09T14:05:18.000Z",
    "start_date": null,
    "end_date": null,
    "is_current": null,
    "is_deleted": false,
    "merged_id": null,
    "link_count": 1,
    "url": "http://localhost:8080/person/109722-Joy_Pollock",
    "image_url": "/images/system/anon.png"
  },
  "values": [ "same_last_name", "mismatched_middle_name", "similar_last_name", "similar_first_name", "common_last_name" ],
  "ranking": 63,
  "automatch": false
};


export const jPollock = {
    "entity": {
        "id": 72481,
        "name": "Jonathan David Pollock",
        "blurb": "Elliott Management executive",
        "summary": "Jonathan David Pollock, Jon is the Co-Chief Executive Officer at Elliott Management Corporation. Mr. Pollock is an Equity Partner at the firm, serves as Co-Chief Investment Officer since 2011 and joined the firm as a Junior Analyst. He is responsible for global situational investing, global trading, and operations. Mr. Pollock is also the Chief Executive Officer and Director at Elliott Advisors (UK) Ltd. Prior to this, he was the Global Head of Situational Investing at the firm. He has also served at E. F. Hutton. Mr. Pollock is a Director of Prime Natural Resources, Inc. and Grant Geophysical, Inc . He is the Chairman of Odyssea Marine, Inc. Mr. Pollock was the Chairman of Horizon offshore Inc. until October of 1999.",
        "website": null,
        "parent_id": null,
        "primary_ext": "Person",
        "created_at": "2011-01-05T09:58:37.000Z",
        "updated_at": "2018-10-26T16:17:03.000Z",
        "start_date": null,
        "end_date": null,
        "is_current": null,
        "is_deleted": false,
        "merged_id": null,
        "link_count": 131,
        "url": "http://localhost:8080/person/72481-Jonathan_David_Pollock",
        "image_url": "/images/system/anon.png"
    },
    "values": [
        "same_last_name",
        "same_middle_name",
        "similar_last_name",
        "common_last_name"
    ],
    "ranking": 155,
    "automatch": false
};


export const exampleItemInfo = {
  "id": 53885,
  "row_data": {
    "owner_key": "5999297",
    "name": "TABACINIC, MORIS",
    "associated_advisors": [
      {
        "crd_number": 157288,
        "name": "NCH CAPITAL INC.",
        "id": 11487,
        "dataset_key": "157288"
      },
      {
        "crd_number": 159768,
        "name": "ROSEMOUNT CAPITAL LIMITED",
        "id": 11437,
        "dataset_key": "159768"
      }
    ],
    "data": [
      {
        "filing_id": 1095161,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "DIRECTOR",
        "acquired": "04/1997",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20170101_20170331.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 159768
      },
      {
        "filing_id": 1072861,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "PRINCIPAL",
        "acquired": "08/1993",
        "ownership_code": "NA",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20170101_20170331.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1072861,
        "scha_3": "",
        "schedule": "B",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "NCH ADVISERS INC.",
        "title_or_status": "SHAREHOLDER",
        "acquired": "08/1993",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20170101_20170331.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1110908,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "PRINCIPAL",
        "acquired": "08/1993",
        "ownership_code": "NA",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20170401_20170630.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1110908,
        "scha_3": "",
        "schedule": "B",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "NCH ADVISERS INC.",
        "title_or_status": "SHAREHOLDER",
        "acquired": "08/1993",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20170401_20170630.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1202770,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "DIRECTOR",
        "acquired": "04/1997",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20180101_20180331.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 159768
      },
      {
        "filing_id": 1160842,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "PRINCIPAL",
        "acquired": "08/1993",
        "ownership_code": "NA",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20180101_20180331.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1160842,
        "scha_3": "",
        "schedule": "B",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "NCH ADVISERS INC.",
        "title_or_status": "SHAREHOLDER",
        "acquired": "08/1993",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20180101_20180331.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1241183,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "PRINCIPAL",
        "acquired": "08/1993",
        "ownership_code": "NA",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20180701_20180930.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1241183,
        "scha_3": "",
        "schedule": "B",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "NCH ADVISERS INC.",
        "title_or_status": "SHAREHOLDER",
        "acquired": "08/1993",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20180701_20180930.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1257205,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "PRINCIPAL",
        "acquired": "08/1993",
        "ownership_code": "NA",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20181001_20181231.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1257205,
        "scha_3": "",
        "schedule": "B",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "NCH ADVISERS INC.",
        "title_or_status": "SHAREHOLDER",
        "acquired": "08/1993",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20181001_20181231.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 157288
      },
      {
        "filing_id": 1257233,
        "scha_3": "Y",
        "schedule": "A",
        "name": "TABACINIC, MORIS",
        "owner_type": "I",
        "entity_in_which": "",
        "title_or_status": "DIRECTOR",
        "acquired": "04/1997",
        "ownership_code": "D",
        "control_person": "Y",
        "public_reporting": "N",
        "owner_id": "5999297",
        "filename": "IA_Schedule_A_B_20181001_20181231.csv",
        "owner_key": "5999297",
        "advisor_crd_number": 159768
      }
    ],
    "class": "IapdDatum::IapdOwner"
  },
  "match_data": null,
  "created_at": "2019-04-23T21:38:24.000Z",
  "updated_at": "2019-04-23T21:38:24.000Z",
  "primary_ext": "person",
  "entity_id": null,
  "dataset_key": "5999297"
};
