production:
  adapter: postgresql
  encoding: unicode
  reconnect: true
  sslmode: prefer
  pool: 15
  database: <%= Rails.application.credentials.dig(:database, :name) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>

development:
  adapter: postgresql
  encoding: unicode
  database: littlesis
  pool: 15
  username: littlesis
  password: themanbehindthemanbehindthethrone
  host: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: littlesis_test
  username: littlesis
  password: themanbehindthemanbehindthethrone
  host: postgres
