#!/usr/bin/env ruby
#------------------------------------------------------------------+
# cleans ny disclosure data
# See process_ny_disclosures for example use
#------------------------------------------------------------------+
require 'csv'
require 'date'

ROW_LENGTH = 30

def valid_date?(row)
  valid = true
  row[5..6].each do |date|
    next if date == "" || date == '\N'
    begin
      DateTime.strptime(date, '%m/%d/%Y')
    rescue ArgumentError
      valid = false
    end
  end
  valid
end

ARGF.each do |line|
  line.encode!(invalid: :replace, replace: '')
  begin
    CSV.parse(line) do |row|
      # starts off as bad...gotta prove your validity...
      good_row = false

      if row.length == ROW_LENGTH
        good_row = true if valid_date?(row)
      end

      if good_row
        $stdout.puts row.to_csv
      else
        $stderr.puts line
      end
    end
  rescue CSV::MalformedCSVError
    $stderr.puts line
  end
end
