#!/bin/sh

help() {
    cat <<HELP
littlesis data <command> <dataset>

 download | downloads original dataset
 extract  | creates csvs
 load     | loads data into the littlesis database
 export   | creates sql archives
 report   | table statistics
HELP
}

run_ruby() {
    echo "$1"
    littlesis runner "$1"
}

command="report"

case $1 in
    download)
        command="download"
        shift ;;
    extract)
        command="extract"
        shift ;;
    load)
        command="load"
        shift ;;
    export)
        command="export"
        shift ;;
    report)
        command="report"
        shift;;
    *)
        help
        exit 1
        ;;
esac

dataset="$1"

if test -z "$dataset"; then
   echo "missing dataset"
   exit 1
fi


case $command in
    download)
        run_ruby "ExternalDataset.public_send('$dataset').download"
        ;;
    extract)
        run_ruby "ExternalDataset.public_send('$dataset').extract"
        ;;
    load)
        run_ruby "ExternalDataset.public_send('$dataset').load"
        ;;
    export)
        run_ruby "ExternalDataset.public_send('$dataset').export"
        ;;
    report)
        run_ruby "ExternalDataset.public_send('$dataset').report"
        ;;
esac
